# Generated by Django 4.2.10 on 2025-01-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_arabic',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
