# Generated by Django 4.2.10 on 2025-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_file_category_name_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
