# Generated by Django 4.2.10 on 2024-11-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_cat_book_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs/Book'),
        ),
    ]
