# Generated by Django 4.2.10 on 2025-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_category_book_alter_book_fav_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
