# Generated by Django 4.2.10 on 2025-02-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_file'),
        ('books', '0006_book_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
