# Generated by Django 4.2.10 on 2025-03-13 17:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_fav',
            unique_together={('user', 'book')},
        ),
    ]
