name: binko
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3
  equatable: ^2.0.7
  flutter_widget_from_html: ^0.15.3
  cached_network_image: ^3.4.1
  awesome_notifications: ^0.10.0
  collection: ^1.19.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  bot_toast: ^4.1.3
  lottie: ^3.3.1
  page_transition: ^2.2.1
  flutter_snake_navigationbar: ^0.6.1
  introduction_screen: ^3.1.14
  animated_theme_switcher: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  injectable_generator: ^2.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/svgs/
    - assets/lottieFiles/
  fonts:
    - family: Leckerli
      fonts:
        - asset: assets/fonts/Leckerli_One/LeckerliOne-Regular.ttf
    - family: LoveYa
      fonts:
        - asset: assets/fonts/Love_Ya_Like_A_Sister/LoveYaLikeASister-Regular.ttf
    - family: Markazi
      fonts:
        - asset: assets/fonts/Markazi_Text/MarkaziText-VariableFont_wght.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart